---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Include suitable role for target distribution family
      ansible.builtin.include_role:
        name: 'refresh_update_{{ os_distro }}'
