---
- hosts: user.cloud-user
  become: true
  remote_user: cloud-user
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: 'ansible_key'

  tasks:

    - name: Include suitable role for target distribution family
      ansible.builtin.include_role:
        name: 'refresh_update_redhat'

- hosts: user.debian
  become: true
  remote_user: debian
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: 'ansible_key'

  tasks:

    - name: Include suitable role for target distribution family
      ansible.builtin.include_role:
        name: 'refresh_update_debian'

- hosts: user.ubuntu
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: 'ansible_key'

  tasks:

    - name: Include suitable role for target distribution family
      ansible.builtin.include_role:
        name: 'refresh_update_debian'
