---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include suitable role for target distribution family
      ansible.builtin.include_role:
        name: 'refresh_update_{{ ansible_distribution }}'
