---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - servers_specs.yml

  tasks:
    - name: Create servers
      openstack.cloud.server:
        state: present
        name: '{{ item.name }}'
        image: '{{ item.image }}'
        flavor: '{{ item.flavor }}'
        volume_size: '{{ item.vol_size }}'
        boot_from_volume: true
        terminate_volume: true
        key_name: ansible_key
        network: ansible_net
        auto_ip: true
        security_groups: ansible_sg
        metadata:
          group: 'user.{{ item.default_user }}'
        wait: true
      with_items: '{{ servers }}'
